[package]
name = "burli-encode"
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
description = "Brotli encoder for burli"
license = "MIT"
repository = "https://github.com/paddor/burli"
readme = "README.md"
categories = ["compression"]
keywords = ["brotli", "compression", "encoder"]
include = ["/src/**/*", "/README.md", "/CHANGELOG.md"]

[lints]
workspace = true

[features]
default = ["std", "simd"]
std = ["alloc", "burli-core/std", "fearless_simd?/std"]
alloc = ["burli-core/alloc"]
simd = ["dep:fearless_simd", "fearless_simd/libm"]
nightly = ["burli-core/nightly"]
paranoid = ["simd", "burli-core/paranoid"]

[dependencies]
burli-core = { version = "0.2.0", path = "../core", default-features = false }
fearless_simd = { version = "0.7.0", optional = true, default-features = false }

[dev-dependencies]
burli = { path = "../.." }
burli-decode = { path = "../decode" }
