[package]
name = "burli-cat"
version = "0.0.0"
edition = "2024"
rust-version = "1.89"
description = "Concat fragments for burli Brotli streams"
license = "MIT"
repository = "https://github.com/paddor/burli"
readme = "README.md"

[lints]
workspace = true

[features]
default = ["std"]
std = ["alloc", "burli-core/std", "burli-encode/std", "burli-decode/std"]
alloc = ["burli-core/alloc", "burli-encode/alloc", "burli-decode/alloc"]
paranoid = ["burli-core/paranoid", "burli-encode/paranoid", "burli-decode/paranoid"]

[dependencies]
burli-core = { version = "0.0.0", path = "../core", default-features = false }
burli-encode = { version = "0.0.0", path = "../encode", default-features = false }
burli-decode = { version = "0.0.0", path = "../decode", default-features = false }

[dev-dependencies]
rust-brotli = { package = "brotli", version = "8.0.4" }
