[package]
name = "burli-decode"
version = "0.3.0"
edition = "2024"
rust-version = "1.89"
description = "Brotli decoder for burli"
license = "MIT"
repository = "https://github.com/paddor/burli"
readme = "README.md"
categories = ["compression"]
keywords = ["brotli", "compression", "decoder"]
include = ["/src/**/*", "/README.md", "/CHANGELOG.md"]

[lints]
workspace = true

[features]
default = ["std"]
std = ["alloc", "burli-core/std"]
alloc = ["burli-core/alloc"]
nightly = ["burli-core/nightly"]
paranoid = ["burli-core/paranoid"]

[dependencies]
burli-core = { version = "0.3.0", path = "../core", default-features = false }

[dev-dependencies]
burli = { path = "../.." }
